[package]
name = "mlkem-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
libcrux-ml-kem = "0.0.3"
clap = { version = "4.5", features = ["derive"] }
rand = "0.8"
hex = "0.4"

[profile.release]
codegen-units = 1
opt-level = 3
lto = true
